global:
  timeout: 10s
  lite-cache-size: 20
chains:
- key: faucet
  chain-id: gameofzoneshub-1a
  rpc-addr: http://35.233.155.199:26657
  account-prefix: cosmos
  gas: 200000
  gas-prices: 0.025doubloons
  default-denom: doubloons
  trusting-period: 90m
- key: faucet
  chain-id: muzamint
  rpc-addr: http://muzamint.com:26657
  account-prefix: cosmos
  gas: 400000
  gas-prices: 0.000025muza
  default-denom: muza
  trusting-period: 90m
paths:
  ming101:
    src:
      chain-id: muzamint
      client-id: rdavjhcelh
      connection-id: orondvqbuh
      channel-id: dblweqbmoo
      port-id: transfer
      order: ORDERED
    dst:
      chain-id: gameofzoneshub-1a
      client-id: czrwylqftc
      connection-id: ukxhbpjdms
      channel-id: verlvmpcjt
      port-id: transfer
      order: ORDERED
    strategy:
      type: naive
