#!/bin/sh
rly ch delete lameofzoneshub-1
rly ch delete 	Compass
rly ch delete 	achain
rly ch delete 	chainylira
rly ch delete 	dawnsworld
rly ch delete 	dokia
rly ch delete 	dos-ibc
rly ch delete 	hashquarkchain
rly ch delete 	ibc-band-testnet1
rly ch delete 	iqlusionchain
rly ch delete 	irishub
rly ch delete 	kappa
rly ch delete 	kava-ibc
rly ch delete 	konstellation
rly ch delete 	mallowchain
rly ch delete 	melea-11
rly ch delete 	morpheus-ibc-3000
rly ch delete 	newroadchain
rly ch delete 	nibiru-ibc
rly ch delete 	nochainnogain
rly ch delete 	okchain
rly ch delete 	ping-ibc
rly ch delete 	ptpchain
rly ch delete 	setanchain
rly ch delete 	simplystaking
rly ch delete 	stakingfund
rly ch delete 	umbrellachain
rly ch delete 	vitwitchain-1
rly ch delete 	vitwitchain
rly ch delete 	westaking
